// <auto-generated />
namespace BookInfo.Domain.Concrete.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class DeletePublisher : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeletePublisher));
        
        string IMigrationMetadata.Id
        {
            get { return "201402130055498_DeletePublisher"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
